name: FirstPlugin
version: '${project.version}'
main: thor.FirstPlugin
api-version: '1.20'
commands:
  catacombs:
    description: a custom command for catacombs
    permission: FirstPlugin.catacombs
    usage: /<command> [test]
  structure:
    description: manage structures
    permission: FirstPlugin.structure
    usage: /<command> [player]
  tpto:
    description: tp to nearest player
    usage: /<command>
  lobby:
    description: tp to lobby
    usage: /<command>
  create:
    description: write your room
    usage: /<command> [name]